name: Test Action

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - ".github/**"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install

      - name: generate Jest reports
        uses: ShaneHoughton/generate-jest-reports@feat/7
        with:
          outputfile: "output.md"
          coveragedir: "./src/mocks/**.js"
          coveragepct: 80
          branchestrue: true

      - name: Comment on coverage
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          find: |
            /[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g
          replace:
          message-path: |
            ./output.md
