name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - "./src/**"
      - "./tests/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install

      - name: generate Jest reports
        uses: ShaneHoughton/comment-jest-reports@main
        with:
          tests: "./tests"

      - name: Comment on coverage
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          message-path: |
            ./output.txt
